# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11", "pypy3.9"]
        include:
          - os: "ubuntu-20.04"
            python_version: "3.6"

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python_version }}
    - name: set pre-commit cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pre-commit
          ~/.cache/pip
        key: ${{ matrix.python_version }}-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('setup.py') }}

    - name: Use latest pip
      run: python -m pip install --upgrade pip
    - name: Pre-install PyYAML without --pre
      if: ${{ startsWith(matrix.python_version, 'pypy') }}
      # Temporary workaround:
      # PyYAML fails to build with Cython 3.0.0a
      # see https://github.com/yaml/pyyaml/issues/601
      run: pip install PyYAML
    - name: Install dependencies
      run: pip install --pre -e '.[dev]'

    - name: Pre-commit hooks
      if: ${{ matrix.python_version != 'pypy3' && matrix.python_version != '3.6' }}
      run: pre-commit run --all-files
    - name: Test with pytest
      run: pytest
